version: '3'

networks:
  backend:
    external: true

services:
  repository:
    container_name: repository
    hostname: repository
    image: krlsedu/csctracker-repository
    restart: always
    networks:
      - backend
